version: "3.8"

services:
  koudou-api:
    image: koudou-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "${KOUDOU_API_PORT}:80"
    networks:
      - web

networks:
  web:
    external: true
