version: "3.8"

services:
  koudou-api:
    container_name: koudou-api
    image: koudou-api
    env_file:
      - .env
    volumes:
      - koudou-api-logs:/app/logs
    build:
      context: .
      dockerfile: api.Dockerfile
    labels:
      - "traefik.frontend.rule=Host:koudou.api.yzypyzy.com"
      - "traefik.frontend.port=${KOUDOU_API_PORT}"
    ports:
      - "${KOUDOU_API_PORT}:80"
    expose:
      - "${KOUDOU_API_PORT}"
    networks:
      - web
    external_links:
      - db:koudou-db
volumes:
  koudou-api-logs:
networks:
  web:
    external: true
