version: "3.8"
services:
  db:
    container_name: koudou-db
    labels:
      - "traefik.enable=false"
    image: postgres
    env_file:
      - .env
    volumes:
      - koudou-db:/var/lib/postgresql/data/
    networks:
      web:
    ports:
      - "${KOUDOU_DB_PORT}:5432"
  admin:
    container_name: koudou-db-admin
    labels:
      - "traefik.frontend.rule=Host:koudou-db.yzypyzy.com"
      - "traefik.frontend.port=${KOUDOU_DB_ADMIN_PORT}"
    image: adminer
    ports:
      - "${KOUDOU_DB_ADMIN_PORT}:8080"
    expose:
      - ${KOUDOU_DB_ADMIN_PORT}
    networks:
      web:
volumes:
  koudou-db:
networks:
  web:
    external: true
