version: "3.7"
services:
  db:
    container_name: koudou-db
    labels:
      - "traefik.enable=false"
    image: postgres
    env_file:
      - .env
    volumes:
      - koudou-db:/var/lib/postgresql/data/
    networks:
      web:
    ports:
      - "${KOUDOU_DB_PORT}:5432"
volumes:
  koudou-db:
networks:
  web:
